### ISSUE TITLE
Support new ARM template language server

### ISSUE THREAD

**Issue by alex-frankel** [benc-uk/armview-vscode#1]
Hey Ben,

I am a PM on the ARM template deployments team at Microsoft.

In a few days, the Azure Resource Manager Tools extension (azurerm-vscode-tools, repo at https://github.com/microsoft/vscode-azurearmtools) will be updated to introduce a new language server for ARM template files. When the extension is installed, deployment templates will automatically be detected via the $schema and the editor language will be set to "arm-deployment" to enable this new language server.

**How this affects other extensions that work with deployment templates files**
Any extension that wants to have an editing experience for ARM templates should support the "arm-template" language ID instead of (if it depends on azurerm-vscode-tools being installed), or in addition to json/jsonc (if it wants to run with or without the azurerm-vscode-tools extension being installed).

Also note that with this update to the extension we are **introducing better support for // comments and multi-line strings**. Even though JSON does not support these features, they are accepted by the ARM deployment API because our JSON deserializer is [Json.NET](https://www.newtonsoft.com/json) which accepts a more lenient version of JSON.  I noticed that the library you are using throws an error when either of these occur in a template.

Let us know if you have any questions,
Alex

**Comment by benc-uk** [comment]
Hi Alex,
Thanks for getting in touch.

Those changes sound great. I think I'd like to support running without the azurearmtools installed but detecting 'arm-deployment' as a language will definitely help, I'll add it to my extension

The JSON changes are more likely more tricky. I use [jsonlint](https://github.com/zaach/jsonlint) to validate and parse the JSON. I'll have a look and see what the JS equivalent is that supports comments and multi-line strings

**Comment by alex-frankel** [comment]
OK great - ensuring it works with the new language should definitely be the priority. Right now, I cannot enable the viewer on an ARM template when the updated ARM tools extension is running. 

I saw that you made a fix for comments already. I'd guess multi-line strings are infrequently used today, but once we publish that we have better support for it, it will be used more often.

**Comment by alex-frankel** [comment]
I don't think you are checking email on your vacation (good!), but I just sent you the vsix that we are going to release so you can test it out now.

**Comment by benc-uk** [comment]
Thanks! I'll take a look (but yes not really checking work emails). However many would argue that developing this *is* work!

Handling comments was easy thanks to an library I found on NPM

So far I've found [just one template with multi-line strings](https://github.com/Azure/azure-quickstart-templates/blob/master/php-pgsql-freebsd-setup/azuredeploy.json), and as you'd expect the JSON validator in VS Code doesn't like it, and neither does my parser. I'll have a think on how best to handle that

**Comment by alex-frankel** [comment]
It is definitely work :) 

FWIW, I think this is the line that needs to be updated:
https://github.com/benc-uk/armview-vscode/blob/master/src/extension.ts#L41

I think you can change it to:
`if(vscode.window.activeTextEditor.document.languageId != "json" || vscode.window.activeTextEditor.document.languageId != "arm-template") {`

I haven't ever authored an extension before, otherwise I would submit a PR myself

**Comment by benc-uk** [comment]
Thanks Alex.
I’ve tested locally with the updated extension you sent me, and it’s working well. I’ve already rolled the “if JSON or arm-template” logic into the various `languageId` checks ahead of your release.

The thorny one remains supporting multi-line strings. I might have to look into how I could re-use the JSON parser from vscode-azurearmtools

**Comment by alex-frankel** [comment]
If there is not something that can be easily adopted in TS, we may not make a lot of noise about ARM supporting this.

Now that you support the new language ID and comments I think we can close this one and make a separate issue for multi-line strings specifically. Would you like me to do that?

**Comment by benc-uk** [comment]
Thanks Alex. I'll close this and open another
