### ISSUE TITLE
Provide Parameters When Viewing ARM Template

### ISSUE THREAD

**Issue by Altern1ty** [benc-uk/armview-vscode#10]
**Describe the solution you'd like**
Either when you load a template or maybe as an extension setting I would like to set the parameter file used for the template visualization.

**Additional context**
This would be very useful when you have multiple environments which may have many parameter files.

**Comment by benc-uk** [comment]
This is a pretty good idea, and would fix a lot of variable/param resolution problems

**Comment by benc-uk** [comment]
Included in v0.2.0 😄
