### ISSUE TITLE
Display name with whitespace are not encoded

### ISSUE THREAD

**Issue by paule96** [benc-uk/armview-vscode#14]
**Describe the bug**
If you use the tag `displayname` (like described in #2 ) and your value has whitespaces like this `SQL server` the result is not encoded and looks like: `SQL%20server`.

**To Reproduce**

snippet to reproduce:

```json
  {
            "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
            "tags": {
                "displayname": "SQL Database Transparent Data Encryption"
            },
            "apiVersion": "2014-04-01",
            "name": "[concat(variables('servers_DbServer_name'), '/', variables('DbName'), '/current')]",
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[resourceId('Microsoft.Sql/servers/databases', variables('servers_DbServer_name'), variables('DbName'))]"
            ],
            "properties": {
                "status": "Enabled"
            }
        },
```

The graph looks like:

![image](https://user-images.githubusercontent.com/11291885/66032291-76aa9a00-e505-11e9-89d3-44dd8e952bc6.png)

**Comment by benc-uk** [comment]
Ahh, I think I know why this is. Should be easy to fix

**Comment by benc-uk** [comment]
Hi @paule96 I had a hunch I already fixed this, I tried reproducing using your exact JSON and I get a sensible result with spaces correctly showing. I also get an icon displayed, I wonder if you're on an older version? Can I check you are on v0.3.0 ?

![image](https://user-images.githubusercontent.com/14982936/66187633-163e6880-e67d-11e9-8575-8657a91e2f2a.png)

**Comment by paule96** [comment]
oh sorry, you are right. maybe I was at version 2 at this moment. Thanks for your great extension. :)
