### ISSUE TITLE
export the graphic as a .png or .svg

### ISSUE THREAD

**Issue by t2kx** [benc-uk/armview-vscode#15]
FEATURE REQUEST
Additional value could be given to the extension when being able to export to PNG, GIF, SVG, 

from the graph provide a button with export , or ... provide a context menu extension to export the graph

screensnips work too, but it's better to have a direct export as resolution can be better

**Comment by benc-uk** [comment]
Great minds think alike, it's already in the next version, aec9f021cf98cff7c54e66084ff7b43bde79a4ee 😊
I'll be releasing shortly

**Comment by t2kx** [comment]
> Great minds think alike, it's already in the next version, [aec9f02](https://github.com/benc-uk/armview-vscode/commit/aec9f021cf98cff7c54e66084ff7b43bde79a4ee) 😊
> I'll be releasing shortly

seems it it's even that hard as CY has an EXPORT function 
http://js.cytoscape.org/#core/export 
![image](https://user-images.githubusercontent.com/37438394/66256621-09f70000-e790-11e9-93ba-5cacd0cc80fc.png)
I Just realized  ....

**Comment by benc-uk** [comment]
New version released

**Comment by kartben** [comment]
SVG export would actually be super useful, and it doesn't look like it was addressed by aec9f02. I'll try to work on a patch, if nobody beats me to it :)
