### ISSUE TITLE
Files beginning with 'v' in a folder show up incorrectly in Resource details

### ISSUE THREAD

**Issue by Tawnos** [benc-uk/armview-vscode#19]
As shown in screenshot, this should be \v, not a box :)

![image](https://user-images.githubusercontent.com/1546176/73569251-e3379600-441e-11ea-8068-8f86037a09d3.png)

**Comment by benc-uk** [comment]
That's weird, can you share a template that reproduces this?

**Comment by Tawnos** [comment]
In the template, parameters section:

```
    "vmssTemplate": {
      "type": "string"
    },
```

resources section:

```
      {
      "name": "deployVmss",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-05-01",
      "dependsOn": ["deploySupportLogStorageAccount",
"deployDiagnosticsStorageAccount"],
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[parameters('vmssTemplate')]",
          "contentVersion": "[BuildVersion]"
        },
        "parameters": {
```

In the parameters file for the template:

```    "vmssTemplate": {
      "value": "Resources\\virtualMachineScaleSet.Template.json"
    },
```

**Comment by Tawnos** [comment]
In the template, parameters section:

```
    "vmssTemplate": {
      "type": "string"
    },
```

resources section:

```
      {
      "name": "deployVmss",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-05-01",
      "dependsOn": ["deploySupportLogStorageAccount",
"deployDiagnosticsStorageAccount"],
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[parameters('vmssTemplate')]",
          "contentVersion": "[BuildVersion]"
        },
        "parameters": {
```

In the parameters file for the template:

``` 
   "vmssTemplate": {
      "value": "Resources\\virtualMachineScaleSet.Template.json"
    },
```

**Comment by benc-uk** [comment]
It's because you have a double back slash in the value `Resources\\virtualMachineScaleSet`
But I'll check the code that does the escaping for displaying these properties

**Comment by Tawnos** [comment]
The double slash is required to escape the path delimiter. This only affects those parameters that have a "v" after the slashes.

**Comment by benc-uk** [comment]
I was able to reproduce this

This was due to a strange bug in the library I use for parsing the JSON, it turns out it hasn't been updated for years.
I've switched to a newer library (in latest release of this extension) and problem has been resolved

**Comment by Tawnos** [comment]
Thanks @benc-uk :) - normally I'd try to dive in to debug/patch, but right now's a bit hectic for my team.
