### ISSUE TITLE
Is it possible to show the displayName text as label?

### ISSUE THREAD

**Issue by paule96** [benc-uk/armview-vscode#2]
Hi Author,

this extension is super cool. But I use in my templates very often the tag `displayname`. This tag can contain a custom name. This will be interpreted for example by the vscode outline extension for ARM. It would be created if I can show this display names in the graph too.

**Comment by MaximRouiller** [comment]
It is also interpreted by the Visual Studio JSON Outline tool.

This is a must-have for anyone wanting to customize the name of the labels without having to change the name of the resources.

**Comment by benc-uk** [comment]
Interesting. I wasn't aware of this convention. Thanks!

Ok so if `displayName` or `displayname` is present in the tags list, it can take the place of the resources's name field.

That's pretty easy :)

**Comment by MaximRouiller** [comment]
It's definitely a "convention" and not in the spec. It's how people are using some extensions to clarify graphs. Let me see if I can grab an existing template, open it in Visual Studio and show you what is displayed.

**Comment by MaximRouiller** [comment]
Without : 
![image](https://user-images.githubusercontent.com/209384/65772977-5e074200-e109-11e9-8c5f-8b7d3686f3f8.png)

With: 
![image](https://user-images.githubusercontent.com/209384/65773017-77a88980-e109-11e9-81a4-2e1d6f8e56e9.png)

**Comment by MaximRouiller** [comment]
This is present in Visual Studio 2019 Preview and was available for a long time before. The fun part, it doesn't impact functionality as it is a totally opt-in scenario.

**Comment by benc-uk** [comment]
Added in https://github.com/benc-uk/armview-vscode/releases/tag/0.1.0

**Comment by paule96** [comment]
That was fast 👌

**Comment by benc-uk** [comment]
I was already making a lot of changes to support linked templates, this was easy to fit in by comparison 😛
