### ISSUE TITLE
Pressing escape in filter box should cancel the operation, not clear the filter

### ISSUE THREAD

**Issue by Tyriar** [benc-uk/armview-vscode#21]
Currently the behavior is that escape will clear the current filter which is a pain if the filter was a decent length

**Comment by benc-uk** [comment]
Interesting, I'm not handling the escape key in my code anywhere.
When you say "cancel the operation", what would you want the escape key to do?

**Comment by Tyriar** [comment]
@benc-uk it should just hide the box, as if you didn't hit filter at all.
