### ISSUE TITLE
Feature Request: Reverse Dependency Arrows

### ISSUE THREAD

**Issue by JustinGrote** [benc-uk/armview-vscode#26]
If a dependsOn is used in a template (e.g. a reference to a network interface in a VM template), then the arrow is drawn from the VM to the network interface. The dependency is actually the opposite and the diagram would make more sense if the arrow went from the network interface to the VM

![image](https://user-images.githubusercontent.com/15258962/83308813-807fbc80-a1bc-11ea-9a64-674d8dc769e4.png)

The arrow direction could be a toggleable feature depending on preference.

Awesome module! I use it every day.

**Comment by benc-uk** [comment]
Makes sense.
I don't even remember what logic buried deep in the code determines the arrow direction, I can take a look

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
