### ISSUE TITLE
Reference Dependencies

### ISSUE THREAD

**Issue by JustinGrote** [benc-uk/armview-vscode#27]
[Since it is recommended to use implicit dependencies with [reference()] where possible ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-best-practices#resource-dependencies), it would be great if this tool applied the same logic to reference entries as it does to DependsOn entries. Currently none of my reference relationships get modeled.

**Comment by benc-uk** [comment]
I didn't even know this was a thing 😮 
Definitely would make sense to try to support this

**Comment by JustinGrote** [comment]
@benc-uk I call it Terraform style :), though it could use some improvements to be as nice as it is in Terraform.
