### ISSUE TITLE
Running the contributed command: 'armView.start' failed

### ISSUE THREAD

**Issue by dawwa** [benc-uk/armview-vscode#28]
**Describe the bug**
I got this error upon clicking the eye icon button on an opened template json file.

**To Reproduce**
Is there some way to tell what's the reason behind the error? any verbose logging option?

**Additional context**
Name: ARM Template Viewer
Id: bencoleman.armview
Description: Graphically display ARM templates in an interactive map view
Version: 0.4.2
Publisher: Ben Coleman
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=bencoleman.armview

https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#

![image](https://user-images.githubusercontent.com/44714043/83993874-9f432900-a909-11ea-9150-8f1467b75adc.png)

**Comment by benc-uk** [comment]
Can you reproduce this? Does restarting VS Code help?
