### ISSUE TITLE
Unable to install the extension with VS code version 1.36.1

### ISSUE THREAD

**Issue by sunnynazar** [benc-uk/armview-vscode#3]
When trying to install this extension , I get an error that this extension is incompatible with visual studio code verison 1.36.1

Do we need to have a particular version of VS code to have this extension installed ?

**Comment by benc-uk** [comment]
The manifest states 1.38.0 so it won't install on anything older than that

I doesn't *need* that version and I'm sure 1.36 would be fine. However the extension packaging tool doesn't let me set an older version, I've tried and it throws an error when pack I try to package it up.

I'll take another look how I can put an older version in the manifest

**Comment by benc-uk** [comment]
Should be fixed in e7e967edd894d227e4c63d225a6cb16e4adb989a
Release v0.0.7

Please try again

**Comment by sunnynazar** [comment]
Yes , works now.

Thanks.
