### ISSUE TITLE
Icons need updating

### ISSUE THREAD

**Issue by Cairn23** [benc-uk/armview-vscode#30]
Azure and its Icons have been updated since the last Icon update in Sept 19. I have looked at how the icons are associated to the resource type and the file naming. The problem is that the icons have not been updated, an it appears the linking of updates is a manual task as the official files do not follow that used within the app.

**Comment by benc-uk** [comment]
All the icons were refreshed to the new look of Azure in release v0.4.0
https://github.com/benc-uk/armview-vscode/releases/tag/0.4.0

This was back in March of this year
