### ISSUE TITLE
Viewer doesn't refresh if ARM file isn't focused

### ISSUE THREAD

**Issue by JustinGrote** [benc-uk/armview-vscode#32]
Issue Type: <b>Bug</b>

If I'm using something like farmer to generate an ARM file, if ARM viewer is running, it won't refresh unless I change focus to the arm file in vscode.

It should be able to poll the file and refresh on changes regardless of the vscode window state.

Extension version: 0.4.4
VS Code version: Code - Insiders 1.49.0-insider (8e872f41d4ba7807e58938bbf861ca6a22d534aa, 2020-08-20T05:37:43.249Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.56GB free)|
|Process Argv|--crash-reporter-id c46712d6-a98d-4728-ab12-732cb7b0c555|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by benc-uk** [comment]
This is annoying right, I found this a pain too, I don't really know how to fix this

Also...
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
