### ISSUE TITLE
Feature Request: Implement Tenant scope icons

### ISSUE THREAD

**Issue by iTiamo** [benc-uk/armview-vscode#34]
Some resources in the Tenant scope don't seem to have icons yet. The ones I have personally ran into are:

`Microsoft.Management/managementGroups`
`Microsoft.Management/managementGroups/subscriptions`

It would be nice to have them. I have a template that describes management group, subscription and resource group structure. It is hard to exactly visualise the image because the default icon looks a lot like a resource group. See graphic below containing a management group, subscription and deployment with two resource groups.

![image](https://user-images.githubusercontent.com/5354821/95743425-0b57e400-0c92-11eb-8cad-b5740dc31dad.png)

**Comment by benc-uk** [comment]
Good find. I never tried my visualizer much with subscription and management group scoped templates, or templates that create management groups.

Should be easy to add these

**Comment by benc-uk** [comment]
Added to v0.4.5

**Comment by iTiamo** [comment]
Thanks Ben, much appreciated.
