### ISSUE TITLE
Better Support for Evaluating Variables

### ISSUE THREAD

**Issue by ghost** [benc-uk/armview-vscode#35]
**Is your feature request related to a problem? Please describe.**
The extension currently supports parameter files which is useful. We have a lot of situations where we use variables to generate resource names based on a naming convention. The extension seems to support variables derived with ‘concat’ bit not with ‘replace’ or ‘take’.

This affects not just the labels, but the dependencies as well.

**Describe the solution you'd like**
Replicate the logic of the Azure ARM processor and support full variable derivation.

**Describe alternatives you've considered**
Our current workaround is to manually supply all the resource names in the parameters file. This is fine for smaller projects, but for larger projects with 10s of resources (or more) is a lot of manual work and we prefer to automatically generate (or change) resource names based on naming convention.

**Additional context**
Here is an example of one that is working fine in our scenario:
![arm-viewer1](https://user-images.githubusercontent.com/55862976/95791651-8ae6c100-0d2d-11eb-8a09-f5ee8b5277b6.png)

Here is an example of one that is not working:
![arm-viewer2](https://user-images.githubusercontent.com/55862976/95791668-90440b80-0d2d-11eb-8a4c-b329ff79d565.png)

**Comment by benc-uk** [comment]
Thanks for the clear description & screenshots of the issue.
I have to manually re-implement all of the ARM functions in my code, so I picked the most common ones. Seems like `take` and `replace` are newer ARM functions which I missed.

Hopefully shouldn't be too hard to add these

**Comment by benc-uk** [comment]
Added the `take()` function to v0.4.5, the `replace()` function was already supported
