### ISSUE TITLE
Add a CLI

### ISSUE THREAD

**Issue by ghost** [benc-uk/armview-vscode#36]
**Is your feature request related to a problem? Please describe.**
If this extension had a CLI, we could automatically generate these diagrams as part of our pipeline. At the moment you have to manually export from VS Code.

**Describe the solution you'd like**
A CLI that allowed us to specify the input file and parameters file and call the Export function to generate the .png. File path would probably be a relevant command line parameter too.

**Describe alternatives you've considered**
We have looked other extensions, but this one is the best.

**Comment by benc-uk** [comment]
Not a bad idea. It would be quite a lot of work, and my concern is many times the output doesn't look good without some manual intervention, i.e. moving stuff around

I'll investigate

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
