### ISSUE TITLE
Params button should support .jsonc

### ISSUE THREAD

**Issue by JustinGrote** [benc-uk/armview-vscode#39]
**Is your feature request related to a problem? Please describe.**
I save my params in .jsonc so editors don't complain about my comments, but I cannot select it with ARM Viewer because it allows json only

**Describe the solution you'd like**
Allow both json and jsonc in the file picker

**Describe alternatives you've considered**
Rename to .json, doing it now for a workaround but not desirable

**Comment by benc-uk** [comment]
Fixed in 0.4.6
