### ISSUE TITLE
Feature Request: Circular dependencies

### ISSUE THREAD

**Issue by alexangas** [benc-uk/armview-vscode#40]
**Is your feature request related to a problem? Please describe.**
It would be helpful to identify circular dependencies. Particularly as when a deployment errors for this reason, only one resource is listed as the culprit, and not those related to it.

**Describe the solution you'd like**
Red arrows pointing out the circular dependency.

**Describe alternatives you've considered**
Briefly hoping that Microsoft will make ARM templates easier to troubleshoot.

**Additional context**
N/A

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
