### ISSUE TITLE
Resource text is unreadable in ANY form in light mode

### ISSUE THREAD

**Issue by t2kx** [benc-uk/armview-vscode#41]
**Describe the bug**
the font for the asset/resource naming has a bold outline resulting in unreadable text. HOWEVER this works when you go in DARK modes

**To Reproduce**
with any template just open it and look at the output. I am running latest versions of both the extension and VSCode and have for i don't remember how long. See images attached for the issue

**Additional context**
![image](https://user-images.githubusercontent.com/37438394/106360459-ccb96880-6318-11eb-89f1-524388f4bd4e.png)
![image](https://user-images.githubusercontent.com/37438394/106360468-db078480-6318-11eb-8945-f4ce9383927d.png)

**Comment by t2kx** [comment]
PS : thanks for the awesome work your doing on this!

**Comment by marsk32** [comment]
Does anyone have a workaround for this with: Labels are unreadable in light theme? //marsk

**Comment by davidroberts63** [comment]
I've done something to help in a pinch. It's not perfect, but it helps a lot. Two line change to [remove the text outline.](https://github.com/davidroberts63/armview-vscode/commit/0a3843636e4a8ef80b721111a4b37a729cec9683)

The downside is that if the arrows cross underneath the text it looks a bit messy. I'm trying to find a reasonable looking way to get the `text-background-color` to work. But that's getting the wrong color from the theme. Not fully familiar with extension writing in vscode, so I'm fumbling around.

Also, the file is typically located here:
%USERPROFILE%\.vscode\extensions\bencoleman.armview-0.4.5\assets\js\main.js

**Comment by t2kx** [comment]
thanks

**Comment by benc-uk** [comment]
I've finally got around to looking at this project again. Sorry it look it took like ~1 year

Anyhow the text should work now on light and dark themes, use version 0.4.6
