### ISSUE TITLE
Customize Icons for Linked Templates

### ISSUE THREAD

**Issue by dciborow** [benc-uk/armview-vscode#43]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when... I use link templates to organize my ARM templates, which ruin my visualizations.
![image](https://user-images.githubusercontent.com/9027725/116609725-b9f80500-a902-11eb-8ea0-8144c5b3ac2b.png)

**Describe the solution you'd like**
I wish I could do something to swap the pictures for the pictures that would should up for the nested templates. Ideally I would be able to mark this in a way that it would be saved. Perhaps in the metadata field of the linked template resource. Just being able to swap the default icon for the AKS icon would make it look much better for example. 

**Describe alternatives you've considered**
if this could really dig into the nested templates, and figure out everything in there that would be even better.

**Additional context**
Nested template icons that aren't picked up
![image](https://user-images.githubusercontent.com/9027725/116610259-56220c00-a903-11eb-8961-c968c02f9173.png)

![image](https://user-images.githubusercontent.com/9027725/116610272-5ae6c000-a903-11eb-915a-44672a51e66c.png)

![image](https://user-images.githubusercontent.com/9027725/116610288-5f12dd80-a903-11eb-9b52-03878fc5386a.png)

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
