### ISSUE TITLE
String replace uses regex

### ISSUE THREAD

**Issue by p3rh5g** [benc-uk/armview-vscode#46]
**Describe the bug**
When using the string replace function it seems like a regex replace is being used in the viewer.

**To Reproduce**
This is a simple template just to reproduce the problem. With this the name should be `a-b-c`, but instead I get `-----` because the `.` is treated as any character in regex.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "type": "foo",
            "name": "[replace('a.b.c', '.', '-')]"
        }
    ]
}
```

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
