### ISSUE TITLE
Customize arrow- and/or background-color

### ISSUE THREAD

**Issue by cmarker0** [benc-uk/armview-vscode#47]
When using the exported .png file in an markdown (with white background) the arrows disappears,

![image](https://user-images.githubusercontent.com/24533038/125906362-0f9ff808-f307-479b-a128-3ea953d9d628.png)

A solution to this would be the posibility to customize the color of the arrows in the diagram

**Comment by cmarker0** [comment]
@benc-uk has this project been abandoned?

**Comment by benc-uk** [comment]
Not abandoned but on pretty much minimal support from now, for various reasons.
Anyhow, this was just me being lame with my CSS colour choices, and should be fixed in 0.4.6 (latest)
