### ISSUE TITLE
supporting blueprint template artifacts

### ISSUE THREAD

**Issue by jackchenwork** [benc-uk/armview-vscode#48]
**Is your feature request related to a problem? Please describe.**
currently armview-vscode only works for ARM template file, it doesn't work for Azure Blueprints template artifacts ( which is a wrapped ARM template. 

**Describe the solution you'd like**

I would like to see support for blueprints artifacts. you can see some samples artifacts in
https://github.com/Azure/azure-blueprints/blob/master/samples/201-AppNetwork/artifacts/vnet-gateway.json

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
