### ISSUE TITLE
Support for Bicep (with Modules!)

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [benc-uk/armview-vscode#49]
**Is your feature request related to a problem? Please describe.**
Something as useful as this is impeeded by the inability to process Bicep

**Describe the solution you'd like**
Same functionallity regardless of if template file is in bicep or json format

**Describe alternatives you've considered**
Compiling the files manually - but this really breaks the workflow

**Additional context**
As an Azure consltant, I find fewer and fewer hand writing json - most of the major efforts have been Bicep over the past 3 months and seems to becoming near exclusive...

**Comment by benc-uk** [comment]
The [Bicep extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-bicep) has great visualization built in. As such I have no plans to support Bicep, and with the increasing use of Bicep, I'm less & less inclined to put a lot of time into adding features to this extension.
Sorry

**Comment by davidcorbin-atmosera** [comment]
Your Icons were prettier....  That being said I completely agree with the decision.
