### ISSUE TITLE
Unable to view the Graphical display.

### ISSUE THREAD

**Issue by sunnynazar** [benc-uk/armview-vscode#6]
![image](https://user-images.githubusercontent.com/40354767/65513560-bbb64700-dedb-11e9-9037-88b5fe51910a.png)

I am getting error when trying to view the design out of the arm template after installing the extension.

**Comment by iRootkit** [comment]
> ![image](https://user-images.githubusercontent.com/40354767/65513560-bbb64700-dedb-11e9-9037-88b5fe51910a.png)
> 
> I am getting error when trying to view the design out of the arm template after installing the extension.

@sunnynazar
Update to VScode 1.38.1 (August Release) version works for me.

**Comment by benc-uk** [comment]
@irootkit - what version were you on before? I set the required ver to 1.30 but that was a bit of a guess

**Comment by sunnynazar** [comment]
I have 1.36.1 VS code version running.
Let me upgrade to 1.38.1 and see if it works.

**Comment by sunnynazar** [comment]
Upgraded to latest version of VS code , but still there are issues.
![image](https://user-images.githubusercontent.com/40354767/65583033-cc6bc900-df7e-11e9-8e9c-10c3e10fd5f6.png)

**Comment by benc-uk** [comment]
Thanks for trying.

I don't understand why.
Could you open the dev console (Help > Toggle Developer Tools) and post the logs when it happens?

**Comment by mcrosstx** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/40354767/65513560-bbb64700-dedb-11e9-9037-88b5fe51910a.png)
> > I am getting error when trying to view the design out of the arm template after installing the extension.
> 
> @sunnynazar
> Update to VScode 1.38.1 (August Release) version works for me.

Updating to 1.38.1 fixed this issue for me.

**Comment by sunnynazar** [comment]
Removed the extension , re-installed and now it works.

**Comment by iRootkit** [comment]
> @iRootkit - what version were you on before? I set the required ver to 1.30 but that was a bit of a guess

minor to 1.30 i not remember specific version.
