### ISSUE TITLE
Allow visibility of resource to be toggled by type

### ISSUE THREAD

**Issue by richardjharding** [benc-uk/armview-vscode#7]
I have some Arm templates that include a few resources such as SQL, storage container but also include a keyvault with many secrets defined in the template - the large number of key vault secrets distorts the layout - it would be nice to say toggle the visibility of a resource (in my case ```microsoft.keyvault/vaults/microsoft.keyvault/vaults/secrets``` ) to false and hide them

**Comment by benc-uk** [comment]
good idea
I've been thinking about how to better handle large templates, this is definitely something that would help

**Comment by benc-uk** [comment]
I've added a filter option to v0.2.0 https://github.com/benc-uk/armview-vscode#resource-filters
It's a little basic but should help with the issue you've seeing

**Comment by benc-uk** [comment]
Closing for now
