### ISSUE TITLE
Error: param.trim is not a function

### ISSUE THREAD

**Issue by rohancragg** [benc-uk/armview-vscode#8]
I get this error in both template I've tried so far...

**Comment by benc-uk** [comment]
Please can you share the template file? Is that possible?

**Comment by rohancragg** [comment]
I’m afraid not. I’ll try and simplify or obscure the template. Would be good if the error gave a bit more detail though.

Cheers, r.

**Comment by benc-uk** [comment]
I think the error is relating to the `concat()` function, that's the only place in my code where I call `param.trim` so if you can see any places you call `concat()` maybe just send those

You can thank JavaScript for the lack of detail in the error message ;)

**Comment by rohancragg** [comment]
We do use concat a lot.

Can you commit a ‘known good’ template(s) intro his repo so we can clone and at least see the extension working (to eliminate something about my machine being the issue for example)?

**Comment by benc-uk** [comment]
I've tested it with hundreds of templates from the https://github.com/Azure/azure-quickstart-templates repo, and can't reproduce the issue.

For example this one works:
https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-tags/azuredeploy.json

**Comment by benc-uk** [comment]
Hi, @rohancragg the v0.0.8 release I've just published has a try/catch around the `param.trim()` call , it might fix your issue.

**Comment by rohancragg** [comment]
Works fine now! ;-)
